name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: "*"
  pull_request:
    branches: [main]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Demo
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish .NET Core Project
        run: dotnet publish Demo.csproj -c Release -o publish --nologo --no-restore
      - name: Update for GH Pages
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/blazor-hooked\/" \/>/g' publish/wwwroot/index.html
          cp publish/wwwroot/index.html publish/wwwroot/404.html
          touch publish/wwwroot/.nojekyll
      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: Demo/publish/wwwroot
