name: Nuget

on:
  workflow_dispatch:    
  push:
    branches: [ main ]
    tags: "*"
    paths: BlazorHooked/**
  pull_request:
    branches: [ main ]
    paths: BlazorHooked/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BlazorHooked
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: tag
      run: echo ::set-output name=VERSION::$([[ "$GITHUB_REF" == *"/refs/tags/"* ]] && echo ${GITHUB_REF/refs\/tags\//} || echo "1.0.0")
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --no-restore -c release --include-symbols /p:SymbolPackageFormat=snupkg /p:AssemblyVersion=1.0.0.0 /p:Version=${{ steps.tag.outputs.VERSION }}
    - name: Push
      if: github.ref_type == 'tag'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION: ${{ steps.tag.outputs.VERSION }}
      run: dotnet nuget push "**/BlazorHooked.$VERSION.nupkg" -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY"
